version: '3.9'

services:
  db:
    image: postgres:latest
    ports:
      - '13672:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sqlalchemy_examples_db
