
on:
  push:
     branches:
       - main

jobs:
  tests:
    name: Test app
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ci
      POSTGRES_PASSWORD: ci
      APP_URL: http://127.0.0.1:8002/v1/api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install --upgrade -r requirements.txt
      - run: docker compose up -d --build
      - run: sleep 10  # Даем время на запуск контейнеров
      - run: docker compose ps -a  # Проверяем статус контейнеров
      - run: pytest -v tests --junit-xml=test-results.xml # Запускаем тесты
      - run: docker compose logs app  # Выводим логи приложения
        if: always()

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results

  release:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - run: gh release create $(git rev-parse --short HEAD) --generate-notes


  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - run: echo "Deploying..."
