
on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Test app
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ci
      POSTGRES_PASSWORD: ci
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install --upgrade -r requirements.txt
      - run: docker compose up -d --build
      - run: sleep 10  # Даем время на запуск контейнеров
      - run: docker compose ps -a  # Проверяем статус контейнеров
      - run: pytest -v tests  # Запускаем тесты
      - run: docker compose logs app  # Выводим логи приложения
        if: always()
      - run: pytest tests
        env:
          APP_URL: APP_URL=http://127.0.0.1:8002/v1/api

      - run: docker compose logs app
        if: always()