
on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Test app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install --upgrade -r /code/requirements.txt
      - run: docker compose up -d --build
      - run: sleep 10  # Даем время на запуск контейнеров
      - run: docker compose ps -a  # Проверяем статус контейнеров
      - run: pytest -v tests  # Запускаем тесты
      - run: docker compose logs app  # Выводим логи приложения
        if: always()
      - run: pytest tests

      - run: docker compose logs app
        if: always()