
on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Test app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pipenv'
      - run: pip install --no-cache-dir pipenv
      - run: pipenv install --deploy --ignore-pipfile
      - run: docker compose up -d --build
      - run: pytest tests

      - run: docker compose logs app
        if: always()